language: node_js
node_js:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
jobs:
  include:
  - stage: Build docker
    script: "./travis_scripts/docker-build.sh"
    if: branch = master
env:
  global:
  - secure: JbysYPjIRbbt2jGmX4jF01yVOVOg6engLVFSMbXA3vuc3im8KQA9KhjvORUu4p8NjDtani43VyH+rps3BJirbsB3c1JQ8UhOZsbmidhKAL+y55LguRexEP6tI5HE4FnBBf65iQihp1bSEtbzu55yJKw7vYRcrVltXdfvdHG6k7JMLfuggdRINfV2u3QE8Ai+POyKihmupE35Sp6ixeFfebw5BI4hJHQTDlqX/SDIWwiVMMOzQn5E9dmG4emq1U1xpwS5xbPr3QqtoCfnVKHLUzjt948syQPJPp0SHKq3hK0UXdh2bz9HHHLFI1iBJXgdDT7mmzDyMu79/a69qIsbURbQ2WmTWcK62eD7QYb7GM3RSQqsPhZL+IwL7g+nKa1nzTTc/fAJxexgzr6HFXVw9gLDPFl4Fr+BzVORJqeB9j4Cb0BM1uMfyqBLybAA8HcicTdRV2Kviu+IahjQzPqXgBbAPafYgkuXmfTkBlNG2TSSS0mkVRVZLMXsd8FBcGfpCVuDoQQ+3FRLjgS/Ql+nXtvA6hizRI6GJuxTWTCCYTJ8QRb8jSwiJ62SbZmCXJxTO007RkVE7MDK6qApRERHYa/A5c1rLqx2z0tMFAG9DS2uRe1KW50q7y5FX3KFLvhsESqGmhWaJA3aVAXAxe9dSU1I6fszeF/Dq5zhdJG2zs8=
  - secure: KOmHoG6Spwp83c+M+PILHntkzuBej57sV8Kx5gKUv0UvPZrJKDIiAyk+x0XpasG4DRjgCiBm5lcKE8leu2lYkB7YVwUvwGHzxmCGZ+R7iiUSfpWdbvev48WzEUGjx0rC613JhL692K1l7AE+Q+QJG1t5HlYYD0GwO8eoJuLLUJAb3uLUxJgJPcEEDeAAj3Qga79+LHO0m74b1We5tTYLBEjFz6gG5/dBB5izNqn0XI4uATlafWao+bpWG/Dn7BGpcTcZX3KlehfUoqxRQmDVnX//gsOAjy+HkXxk0vsZf9mhIvNW6nmFOkUBhqTt5zlzDMPuINAbbYWXSWJM2Y6Vn2l1vbUtp08YYEoGNRK8TOsYW9FMyuOQ+SwrgnFWEYNXi0/toGaUtMInGMmCjqgKM4cnBohNZh5hrcgUkVWrwwCmTMxf18mbB8hf4e2teH4z+sEkdZ6UEzGH3TG4pdiAi93izo6VWzKpbjoYFeLwF8p75SmDDu+DffCkGjaibnv24M7XsqQcc58ID1Cq8mgB2Fn1LINMXljKLY/gl18C8PjVtnfO3NDm6qc2+lR0eGPi42nh7LBjLGSl9EAHUS9HXh4w1+a+hzwOKFNYr0yzFVulH20aTpKIKijlWxLIrU7Cod96M9maVcmf8lTeeb8RsUfuHoFpzNLi0fOE30fYz0k=
