language: node_js
node_js:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
jobs:
  include:
  - stage: Build docker
    script: "./travis_scripts/docker-build.sh"
    if: branch = master
env:
  global:
  - secure: tzHs2hZo0qtax2u7wApo9pMQBxJvRW2JJdsq5qCMakOZoQx3sqaw+wvpryrPozBLL65XVXzzGoz0s8Q8d4y6upktvvYyYou6e7ebc0N9zfe4zHqxMSQmd24tmhtzIY8/PG9HqPFCGMwDyy62seZ7LiGG07EWWaed3UTZCT08CP+aPmvd26GBoD8unVPsR2cCp/ve7R6dyP3PH6/2YrSs2y+4dp4MI1Cd8SBSqFFCBxmveN/mNQqqELORDjvyYaqk0yRNGP4RLXXoUbURnEd55FZFgoSbF9b5giWGoA6MK2DUngreIepg5XPIiLxQjPb7JTNtPDdW0k3MzmBpVJU7sZMIfC26F15Q5+uFoVfry/NUC3B6HPey178WXjk+HxrqsAwWU0YXM1Ivqh1PcRG64C2R+UmzaAVlEegwaHh+gniDdX1rc1o0Xwp1ZqLkgZug1ChVh4UUziCjUqXssn/wCwj6/HGQj3Y3oF6+xIuy0uZPYaL1V44E/dnkLfXdUgRvI2XdmnewLo7qnQuwC6E0kqiLKEjdMTrB2tfhz0WtNOA2PI6MwWu+dHkMSpLtT+pRF0+cMSei+dtJmmr9fLqJcd+D4yE1EsdVpDmrpM68ShhRCf4H9wtl1DiHXlizQWuay/Eg7GEdusb3U52YFvBb8DmsfN04pWL+hnnjDl821ys=
  - secure: Rd1nLzg3UqBQaK/oe9wOX8Sr+XuMGU3TH8PyBFFVnSkhKy1lpqpcQDfQZn/GfRbF69FQr+GOanKe/kLmJq0x7Xj7Y0Exntj2/yX7Oz47oqHhPACTmKCqeeVIVnate/5j9bagjT1wLvo2chj6PLq/lIgUCGrbZY/EUvUN32GJItKa0J+RFh50bnn34ry4SAh5lD4xGWBibw0Dh9GpVABQTZjKKFF/zioz+r9R3bztAeX2VJgxqDofi6455n9v6kD8mIpWw3/6UnQoyl0vbRErUL5v60iVxMKmWpmzHyfQz+K9IBi8p3Z0W/vYs2Vdbqq6/vGwA1VdQaHVi40aePguP+d3cP/MblfbYJV26Hk2odsEKFCp972i88lBJxnBo9H0TL2s03KR9Z8hOaIKiHMh9yppEf+251Row03vATmafmnFZeeUM+spWLUXe0IxUoica5+cu6kQ2ebhwzOs/DLNbMc/cNg/e43hgXfbMWxquGVxmjxxeDzTgwXmZ6uBaeylRxw9rxDwHtujHLJsuGpX7CK3gpeqhm2fK//WnEZpi0G6p5IB8IhFVHXv9uQ5KPQWWmSHHrPD+UgnpQM0ZapuSYilb02a1Zqw1miBDG1e2im9Gzv+rJfyBX/tKS7WbQxXNS9voL5uLsiQx5WNp8mKO6ovx4qzcIfwbXlMrvHUNdU=
