language: node_js
node_js:
- '8'
sudo: required
services:
- docker
branches:
  only:
  - master
jobs:
  include:
  - stage: Build docker
    script: "./travis_scripts/docker-build.sh"
    if: branch = master
env:
  global:
  - secure: Eo5z77zLWD7jmD7r0SV6WOH1FfUdcLBEI1u3/AKfFEpZF3ND+OzLaWCbW03Zjcuow2kBgrumm3+Mw7roS+jY4HZbaxz4PQh4k3LJwfke1jnex/z+72mdrG5klOWyHC6CZRUrie9UwIkLjQG8gt2wWrYbcLGbctnFMMG85fqAkh473nnrL2HG+sMCXzlAT6yMO5C2LX6c7ZJJZGTZlX1EuTiasgbpj7QYkAn37ACOPcdbCSY0e+kSetVu3RPReyXRMyqsdbt/1uxYrofoTIipShpeGOi+cT7KFLTGZbrHXWar9jfg/a+1C7ysVqpmEWSpkT9gCIVGk89gBChfB2RhO9O2SeSNIWjZvIaJQRO+obQrg0IEcgrAB6sLQpOkffg6Z7UsRDrfh9Zz23PfUeq8gN/AKy+yuwuzFAs9/sExhMeagZp3xBtU2P6HJuuxzmj4UjHkQe6H2MC9YBXDtZWvq8LyArf5CKRiPECTaejz9V/xaYMki7wiccpTMe8dwv2sExim+0FvBAuGk/QHSxnFAmYR5xcumFzMsXpdH4PuCPi9YMtLdp29aRVIuqLY9LFYwVtU6kpYSmSkYSyR+JxthgeatMudzDHuwYB3hQxvGYEYlQVzHvwvmvVxvt/l6mbz/qQrE/44eUUFpy44KwJhXAx+3FXOY5UkWhNF9Z+mXlI=
  - secure: nVsZFLHizenOgXqDVy1DDrFxYKjuW+oQkJskw2R3K9pZ/ulUJbZgE5/kryL0giwZLP43V+wYItT4ApivtJf7f/v36R4fiPr/6a7XFO/AfdaQU5uM7ePgA/y7Vupyfy6Dfn66ntLhQq+TATqyzvZGOJKZGHMtRXdagZ1/A23tfb3TyLI0Tiy47Oci+vZrujBFdU5VJNHLT25Up0i7efGYA2WD+TpT0q63k+Yir/5ElwDGKlrtvTT6e2R7rJGMtFhKyuEX92TJ8Nrtx7Cj33xShC1Em4KOfsVuC1UBWcA3ohSSBzjSRV7mqyX2YQ8S7e77hQDHlQ6ZKHN/jQAF0AynW+Q8vvTO4Nlz22O5uo5TwiCzwySOjfKzl7CSmUCQ3en0kCbh4ied6NIeWURlPVYcwQf7v+EvaAbrf1+wUXNPZrRHeXYKvkG4wZrneLPOXs7jP8b47+cG2U/chdWlva1T/frBbtv4zreqY4IaC1t1ogSZyxAoIsg/Otuhslw1r3qd2Tu2Rqu6SuYLFsdrCE0yUDMafHFsNoRTNvr3uMn54hpuJKvLSEFB+gXVgAlyG4OkOLhSouF9n+eTZUfk4Rem33Bh8W50nEM9nLEM70OtCJo12gfbu2taioSNsMmeSoJYhBRFAanB9xAUuODwX11cZMWd3fGeXLVSc0sY2OVBfGE=
